{% set name = "fswatch" %}
{% set version = "1.13.0" %}
{% set sha256 = "90bcf0e02fa586251aa3233cb805ca4087e81de2c5960150a0676cc42f8534bb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/emcrisostomo/fswatch/releases/download/{{ version }}/fswatch-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: true  # [win]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - libtool                # [unix]
  host:

test:
  commands:
    - fswatch --help
    - test -d "${PREFIX}/include/libfswatch"              # [unix]
    - test -f "${PREFIX}/lib/libfswatch${SHLIB_EXT}"      # [unix]
    - conda inspect linkages -p "${PREFIX}" "{{ name }}"  # [unix]
    - conda inspect objects -p "${PREFIX}" "{{ name }}"   # [osx]

about:
  home: https://github.com/emcrisostomo/fswatch
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: |
    "A cross-platform file change monitor with multiple backends: Apple OS X
     File System Events, *BSD kqueue, Solaris/Illumos File Events Notification,
     Linux inotify, Microsoft Windows and a stat()-based backend."

extra:
  recipe-maintainers:
    - jakirkham
